### ISSUE TITLE
Potential Bug/Typo

### ISSUE THREAD

**Issue by anantzoid** [HsinYingLee/DRIT#11]
I think line 157 in `models.py` should be
`self.z_content_recon_a, self.z_content_recon_b = self.enc_c.forward(self.fake_A_encoded, self.fake_B_encoded)` instead of
`self.z_content_recon_b, self.z_content_recon_a = self.enc_c.forward(self.fake_A_encoded, self.fake_B_encoded)`.

**Comment by hytseng0509** [comment]
No, that one is correct. `self.fake_A_encoded` is decoded from `self.z_content_b` (Line 147), so the encoded content feature should be `self.z_content_recon_b`. This is the forward translation in the proposed cross-cycle consistency. For more details please refer to Section 3.2 in our [paper](https://arxiv.org/pdf/1808.00948.pdf).
