### ISSUE TITLE
The link to download the dataset is 403

### ISSUE THREAD

**Issue by Hshihua** [HsinYingLee/DRIT#12]
Hi,
  Thanks for your sharing, while I want to download the dataset which you shared, I encountering "403", could you please tell me what is going on?

**Comment by hytseng0509** [comment]
Which link did you use to download the dataset?

**Comment by Hshihua** [comment]
Thanks for your reply, I use this link: http://vllab.ucmerced.edu/hylee/DRIT/datasets.

**Comment by hytseng0509** [comment]
You can follow the instruction [here](https://github.com/HsinYingLee/DRIT#datasets) and use our script to download the dataset.
Or you can download it manually:
`portrait`: http://vllab.ucmerced.edu/hylee/DRIT/datasets/portrait
`cat2dog`: http://vllab.ucmerced.edu/hylee/DRIT/datasets/cat2dog
