### ISSUE TITLE
If total domains are 4

### ISSUE THREAD

**Issue by redhat12345** [HsinYingLee/DRIT#13]
Hi,

Thank you so much for the code and paper. My dataset contains 4 domains. The dataset structure is: trainA, trainB, trainC, trainD, testA, testB, testC, testD. How can I use this code for if 4 domains are exist in the dataset? Thanks in advanced.

**Comment by hytseng0509** [comment]
1. Choose the two domains between which you want to perform the translation.
2. Rename the corresponding folders to `trainA`, `trainB`, `testA`, and `testB`.

For example, if you want to perform the translation between A domain and C., You need to rename `trainC` to `trainB` and `testC` to `testB`.
