### ISSUE TITLE
About pretrain model

### ISSUE THREAD

**Issue by shz1314** [HsinYingLee/DRIT#16]
Hi，
     Shall you send me the pretrain model weight? My email address is haoze_song_jnu@163.com

**Comment by smile123fly** [comment]
Did the author send you the pretrain model weight and can you forward me a copy? Thank you! My email address is smile2fly123@163.com

**Comment by HsinYingLee** [comment]
The download link to the Yosemite model http://vllab.ucmerced.edu/hylee/DRIT/model/ysmt_DRIT_1200.pth

**Comment by xq821272536** [comment]
Thank you. But it shows "The page you are looking for cannot be found."

**Comment by HsinYingLee** [comment]
Hi, link updated.

**Comment by xq821272536** [comment]
thank you~
