### ISSUE TITLE
Different batch size

### ISSUE THREAD

**Issue by XuYunqiu** [HsinYingLee/DRIT#18]
Hi, thanks for your great work about GAN.
I found in your paper you said you use batch size of 1, but in this code the default training batch size is set to 2. 
I would like to ask is there any special training trick about batch size?

**Comment by hytseng0509** [comment]
Hi,

Please refer to [model.py](https://github.com/HsinYingLee/DRIT/blob/a590bb4c892d19d2168c7d527364ec842adea1a8/src/model.py#L123), we use `encoded` image as the input image for the main training (disentangled representation, cross-cycle consistency). As for `random` image, we only use it to train the discriminator in latent regression (refer [here](https://github.com/HsinYingLee/DRIT/blob/a590bb4c892d19d2168c7d527364ec842adea1a8/src/model.py#L217)). We found that this would yield more diverse results.
