### ISSUE TITLE
write_img isssue

### ISSUE THREAD

**Issue by XuYunqiu** [HsinYingLee/DRIT#19]
Hi,
I found if the maximal size of the train sets (trainA or trainB) is an integer multiple of _opt.d_iter_, the model will not execute _model.update_D(images_a, images_b)_ when each epoch ends

https://github.com/HsinYingLee/DRIT/blob/a590bb4c892d19d2168c7d527364ec842adea1a8/src/train.py#L46-L52
https://github.com/HsinYingLee/DRIT/blob/a590bb4c892d19d2168c7d527364ec842adea1a8/src/train.py#L69-L70

As a result, there are some problems about saving result images. The input images will update to a new pair, while the other images remain unchanged.

For example, my trainA contains 2733 images, and I set   _opt.d_iter=3_. And here is my result grid
![gen_00144](https://user-images.githubusercontent.com/23272227/45792536-b454d000-bcc0-11e8-8da4-4c13f0fa3cef.jpg)
 If I delete 1 image in trainA, it works well

**Comment by hytseng0509** [comment]
Thanks for pointing out the problem. We fix the corresponding code. Please let us know if the problem still exists.
