### ISSUE TITLE
Some errors in your paper

### ISSUE THREAD

**Issue by Hshihua** [HsinYingLee/DRIT#20]
Thanks for your sharing. When I read your DRIT paper which was downloaded from arxiv.org, I find some writing errors in your paper.  In formula(5),  just as shown in following image, there are extra close parentheses. 
![image](https://user-images.githubusercontent.com/36783415/46252306-bde8ef80-c499-11e8-8037-0a42dd72221e.png)

**Comment by hytseng0509** [comment]
Thanks for pointing it out.
