### ISSUE TITLE
Difference with MUNIT?

### ISSUE THREAD

**Issue by Cuiyirui** [HsinYingLee/DRIT#26]
The idea of this paper same to MUNIT https://github.com/NVlabs/MUNIT
Both propose share content space and separate style space. I want to know the differences.

**Comment by HsinYingLee** [comment]
MUNIT and DRIT are concurrent works sharing a similar high-level idea. The key differences lie in the way they combine content and attribute features. MUNIT adopts AdaIn to transform content features based on attribute features, while DRIT provides two options: 1. For color-variation translation, simple concatenation works well. 2. For shape-variation translation, we adopt element-wise feature transformation.

**Comment by Cuiyirui** [comment]
> MUNIT and DRIT are concurrent works sharing a similar high-level idea. The key differences lie in the way they combine content and attribute features. MUNIT adopts AdaIn to transform content features based on attribute features, while DRIT provides two options: 1. For color-variation translation, simple concatenation works well. 2. For shape-variation translation, we adopt element-wise feature transformation.

Thanks, I understood it.
