### ISSUE TITLE
kl loss in code

### ISSUE THREAD

**Issue by MeiHuanshan** [HsinYingLee/DRIT#37]
Thank you for your excellent work and open the code! I am very interested in your work.When I read code, I found
![image](https://user-images.githubusercontent.com/29477175/66552922-ce3bac00-eb7c-11e9-85b8-5dbb4be894e4.png)
here kl loss seems like regularzation, but in paper kl loss is kl distance between z_attr and N(0,1)

**Comment by HsinYingLee** [comment]
Hi,
KL loss is applied to attribute vectors in the concat setting. However, we recently verified that removing KL loss will not degrade the performance. We'll update the paper and code soon.

**Comment by MeiHuanshan** [comment]
Thank you very much for your reply! I get it. Best wishes

**Comment by israrbacha** [comment]
Hi i want to train this on two gpu's, can you guide how to change the code?

**Comment by hytseng0509** [comment]
You can refer to the implementation of using multi-GPUs from [BicycleGAN](https://github.com/junyanz/BicycleGAN).

**Comment by LynnHo** [comment]
@hytseng0509 Hi, what's the l2 regularization for? Is there a relation with KL? And why there is an l2 reg on z_content.
