### ISSUE TITLE
where is the supplementary material ?

### ISSUE THREAD

**Issue by taki0112** [HsinYingLee/DRIT#7]
Hi
very nice work.

I can't find `supplementary material`

where is ? can you give me ?

Thank you

**Comment by hytseng0509** [comment]
We provide the detail of network architecture and more translation results in the supplementary material.
For the detail of network architecture, please refer to [network.py](https://github.com/HsinYingLee/DRIT/blob/master/src/networks.py). We show more translation results on our [project page](http://vllab.ucmerced.edu/hylee/DRIT/).
