### ISSUE TITLE
Gradient of Style Encoder - Bug?

### ISSUE THREAD

**Issue by affromero** [HsinYingLee/DRIT#8]
Hello, 

From your code, you only update the gradients of the style encoder in `backward_EG` only from the KL loss. However, as far as I can see, `backward_G_alone` also provides gradients with `loss_z_L1`, and you are calling `self.enc_c_opt.step()` after this function, instead of `self.enc_a_opt.step()`. Does it make sense? Am I missing something here?

Thank you.

**Comment by hytseng0509** [comment]
We don't optimization the attribute encoder for latent regression. We found that would force the generator to generate more diverse results.
