### ISSUE TITLE
what difference using concat ?

### ISSUE THREAD

**Issue by taki0112** [HsinYingLee/DRIT#9]
Hi
I don't know what difference `E_attr_concat` and `E_attr`

what you use ? `concat` ? or `no_concat` ?
Is there a difference in performance?
can you tell me ? 

thank you

**Comment by hytseng0509** [comment]
As mentioned in [README.md](https://github.com/HsinYingLee/DRIT/blob/master/README.md), we provide two ways to combine content and attribute feature. The first one is the simple feature concatenation (`--concat 1`) and the second one is the feature-wise transformation (`--concat 0`). For feature-wise transformation, we learn to scale and bias content feature according to attribute feature.

We use feature concatenation for shape preserving translation (winter <-> summer). As for the translation with shape variation (e.g., cat <-> dog), we find feature-wise transformation would have better results.

**Comment by taki0112** [comment]
What is the performance difference between a `multi-scale discriminator` and `no-multi scale discriminator`?
